### ISSUE TITLE
Hi, Where can i find the code for running the baseline comparisons as shown in the paper? Thanks!

### ISSUE THREAD

**Issue by Srujan-D** [marmotlab/CAtNIPP#1]

**Comment by wyzh98** [comment]
We implemented those baselines ourselves and can send them to you. You can drop your email here.

**Comment by Srujan-D** [comment]
Great- my email is srujan[dot]deolasee[at]gmail[dot]com 

Thanks!

**Comment by caomuqing** [comment]
Could you also send me the baseline algorithm code? Thank you! muqingc@andrew.cmu.edu
